package com.example.tsellstore;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.app.WindowDecorActionBar;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;

import com.example.tsellstore.NavigationComponent.Dashbord.HorizontalProduct.HorizontalScrollProductModel;
import com.example.tsellstore.NavigationComponent.Dashbord.MainRecyclerView.DashbordAdapter;
import com.example.tsellstore.NavigationComponent.Dashbord.MainRecyclerView.DashbordModel;
import com.example.tsellstore.NavigationComponent.Dashbord.ViewPager.SliderModel;

import java.util.ArrayList;
import java.util.List;

import static com.example.tsellstore.DatabaseQueries.lists;
import static com.example.tsellstore.DatabaseQueries.loadFragmentData;
import static com.example.tsellstore.DatabaseQueries.loadedCategoriesNames;


public class CategoryActivity extends AppCompatActivity {

    private RecyclerView category_recyclerview;
    private DashbordAdapter dashbordAdapter;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_category);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        String title = getIntent().getStringExtra("CategoryName");
        getSupportActionBar().setTitle(title);

        category_recyclerview = (RecyclerView) findViewById(R.id.category_recyclerview);

        //////////////////////////--------Horizontal product Layout---------->>>>>>>>>>>>>>>>>>>>>
        ////////////////////////////--------Main Recycler View ------------------>>>>>>>>>>>>>>>>>>>
        LinearLayoutManager testingLayoutManager = new LinearLayoutManager(this);
        testingLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        category_recyclerview.setLayoutManager(testingLayoutManager);


        //at first check krbo user 1st e data access korche ki na jodi access kore tobe oi data amra re use krbo
        int listPosition = 0;

        for(int x= 0; x <loadedCategoriesNames.size(); x++){
            if(loadedCategoriesNames.get(x).equals(title.toUpperCase())){
                listPosition=x;
            }
        }

        //notun data niye asbo database theke
        if(listPosition == 0){
            loadedCategoriesNames.add(title.toUpperCase());
            lists.add(new ArrayList<DashbordModel>());
            dashbordAdapter = new DashbordAdapter(lists.get(loadedCategoriesNames.size() - 1));
            loadFragmentData(dashbordAdapter,this,loadedCategoriesNames.size() - 1,title);
        }else {
            dashbordAdapter = new DashbordAdapter(lists.get(listPosition));
        }
        category_recyclerview.setAdapter(dashbordAdapter);
        dashbordAdapter.notifyDataSetChanged();

    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.search_item, menu);
        return true;
    }

    //autogenerated when we create a NavigationDrawer Activity
    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {

        switch (item.getItemId()) {
            case R.id.main_search:
                break;
            case android.R.id.home:
                finish();
                break;
        }

        return super.onOptionsItemSelected(item);
    }
}
