package com.example.tsellstore.NavigationComponent;

import android.content.Intent;
import android.os.Bundle;
import android.view.MenuItem;
import android.view.View;
import android.view.Menu;
import android.widget.FrameLayout;
import android.widget.TextView;
import android.widget.Toast;

import com.example.tsellstore.NavigationComponent.Dashbord.DashbordFragment;
import com.example.tsellstore.NavigationComponent.MyCart.MyCartFragment;
import com.example.tsellstore.NavigationComponent.MyWishList.MyWishListFragment;
import com.example.tsellstore.NavigationComponent.Myorders.MyOrdersFragment;
import com.example.tsellstore.R;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;
import com.google.android.material.navigation.NavigationView;

import androidx.annotation.NonNull;
import androidx.appcompat.app.ActionBarDrawerToggle;
import androidx.appcompat.widget.Toolbar;
import androidx.core.view.GravityCompat;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentTransaction;
import androidx.navigation.NavController;
import androidx.navigation.Navigation;
import androidx.navigation.ui.AppBarConfiguration;
import androidx.navigation.ui.NavigationUI;
import androidx.drawerlayout.widget.DrawerLayout;
import androidx.appcompat.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity implements NavigationView.OnNavigationItemSelectedListener {

    private AppBarConfiguration mAppBarConfiguration;

    private static final int HOME_FRAGMENT = 0;
    private static final int CART_FRAGMENT = 1;
    private static final int MY_ORDER_FRAGMENT = 2;
    private static final int MY_WISHLIST_FRAGMENT = 3;

    private static int currentFragment = -1;
    NavigationView navigationView;
    private FrameLayout frameLayout;
    private TextView actionBar_logo;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        actionBar_logo=(TextView) findViewById(R.id.actionBarLogo);

        getSupportActionBar().setDisplayHomeAsUpEnabled(false);

        DrawerLayout drawer = findViewById(R.id.drawer_layout);
        navigationView = findViewById(R.id.nav_view);

        ActionBarDrawerToggle actionBarDrawerToggle = new ActionBarDrawerToggle(
                this,
                drawer,
                toolbar,
                R.string.openNavBar,
                R.string.closeNavBar
        );
        drawer.addDrawerListener(actionBarDrawerToggle);
        actionBarDrawerToggle.syncState();
        navigationView.setNavigationItemSelectedListener(this);
        navigationView.getMenu().getItem(0).setChecked(true);
        frameLayout = (FrameLayout) findViewById(R.id.main_framLayout);

        setFragment(new DashbordFragment(), HOME_FRAGMENT);


        // Passing each menu ID as a set of Ids because each
        // menu should be considered as top level destinations.

        /**
         * -------->>>>>>>>>>>>>>>>>>>>>>by default set the navigation first menu enablede
         */
        //by default set the navigation first menu enablede
        //
        //------------------------"""""""""""""""""""

        //autogenerated when we create a NavigationDrawer Activity

//        mAppBarConfiguration = new AppBarConfiguration.Builder(
//                R.id.nav_dashbord, R.id.nav_myorders, R.id.nav_rewards, R.id.nav_wishlist, R.id.nav_cart,
//                R.id.nav_account, R.id.nav_signout)
//                .setDrawerLayout(drawer)
//                .build();
//        NavController navController = Navigation.findNavController(this, R.id.nav_host_fragment);
//        NavigationUI.setupActionBarWithNavController(this, navController, mAppBarConfiguration);
//        NavigationUI.setupWithNavController(navigationView, navController);

    }

    @Override
    public void onBackPressed() {
        DrawerLayout drawer = findViewById(R.id.drawer_layout);
        if(drawer.isDrawerOpen(GravityCompat.START)){
            drawer.closeDrawer(GravityCompat.START);
        }else {
            if(currentFragment == HOME_FRAGMENT){
                super.onBackPressed();
            }else {
                actionBar_logo.setVisibility(View.VISIBLE);
                invalidateOptionsMenu();
                setFragment(new DashbordFragment(), HOME_FRAGMENT);
                navigationView.getMenu().getItem(0).setChecked(true);
            }

        }

    }

    //autogenerated when we create a NavigationDrawer Activity
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        if (currentFragment == HOME_FRAGMENT) {
            getSupportActionBar().setDisplayShowTitleEnabled(false);
            getMenuInflater().inflate(R.menu.main, menu);
        }
        return true;
    }


    //autogenerated when we create a NavigationDrawer Activity
    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {

        switch (item.getItemId()) {
            case R.id.main_search:
                break;
            case R.id.main_notification:
                break;
            case R.id.main_cart:
                gotoFragment("My Cart",new MyCartFragment(),CART_FRAGMENT);
                break;
        }

        return super.onOptionsItemSelected(item);
    }

    private void gotoFragment(String title,Fragment fragment,int fragmentNo) {
        actionBar_logo.setVisibility(View.GONE);
        getSupportActionBar().setDisplayShowTitleEnabled(true);
        getSupportActionBar().setTitle(title);
        invalidateOptionsMenu();
        setFragment(fragment, fragmentNo);
        if(fragmentNo == CART_FRAGMENT) {
            navigationView.getMenu().getItem(3).setChecked(true);
        }
    }

    //autogenerated when we create a NavigationDrawer Activity
//    @Override
//    public boolean onSupportNavigateUp() {
//        NavController navController = Navigation.findNavController(this, R.id.nav_host_fragment);
//
//        return NavigationUI.navigateUp(navController, mAppBarConfiguration)
//                || super.onSupportNavigateUp();
//    }



    @Override
    public boolean onNavigationItemSelected(@NonNull MenuItem item) {
        int id = item.getItemId();
        switch (id) {
            case R.id.nav_dashbord:
                actionBar_logo.setVisibility(View.VISIBLE);
                invalidateOptionsMenu();
                setFragment(new DashbordFragment(), HOME_FRAGMENT);
                break;
            case R.id.nav_myorders:
                gotoFragment("My Order",new MyOrdersFragment(),MY_ORDER_FRAGMENT);
                break;
            case R.id.nav_rewards:

                break;
            case R.id.nav_cart:
                gotoFragment("My Cart",new MyCartFragment(),CART_FRAGMENT);
                //setFragment(new MyCartFragment(),CART_FRAGMENT);
                break;
            case R.id.nav_wishlist:
                gotoFragment("My Wishlist",new MyWishListFragment(),MY_WISHLIST_FRAGMENT);
                break;
            case R.id.nav_account:
                break;
            default:
                Toast.makeText(this, "ILoVeYou-Sweetie", Toast.LENGTH_SHORT).show();

        }
        DrawerLayout drawer = findViewById(R.id.drawer_layout);
        drawer.closeDrawer(GravityCompat.START);
        return true;
    }

    @Override
    public void onPointerCaptureChanged(boolean hasCapture) {

    }

    private void setFragment(Fragment fragment,int fragmentNo) {
        if(fragmentNo != currentFragment) {
            currentFragment = fragmentNo;
            FragmentTransaction fragmentTransaction = getSupportFragmentManager().beginTransaction();
            fragmentTransaction.setCustomAnimations(R.anim.fade_in, R.anim.fade_out);
            fragmentTransaction.replace(frameLayout.getId(), fragment);
            fragmentTransaction.commit();
        }
    }
}